<script lang="ts">
	import { sharedValue } from '../../../../shared-external/value';

	// Issue #2942 source-map drift: the import above reaches OUTSIDE the
	// workspace root and GROWS when rewritten (+N bytes per added `../`),
	// shifting every generated byte offset AFTER it. The deliberate TS2322 below
	// must still map back to the correct line AND column in this `.svelte`
	// source. Before the drift fix the column was shifted by the grown-import
	// byte delta.
	//
	// Kept free of `.svelte` imports so the (out-of-scope) `.svelte` ->
	// `.svelte.js` rewrite cannot perturb the asserted column.
	const bad: string = sharedValue;
</script>

<p>{bad}</p>
