//! Source map builder for tracking position mappings during transformation.

use crate::{ByteOffset, Span};
use text_size::TextSize;

/// Applies a signed byte `shift` to a `ByteOffset`, saturating at 0.
#[inline]
fn apply_shift(offset: ByteOffset, shift: i64) -> ByteOffset {
    let result = i64::from(u32::from(offset)) + shift;
    TextSize::from(result.max(0) as u32)
}

/// A single mapping from generated position to original position.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Mapping {
    /// The span in the generated output.
    pub generated: Span,
    /// The span in the original source.
    pub original: Span,
}

/// A source map that tracks position mappings from generated code back to original source.
#[derive(Debug, Clone, Default)]
pub struct SourceMap {
    /// List of mappings, sorted by generated position.
    mappings: Vec<Mapping>,
}

impl SourceMap {
    /// Creates a new empty source map.
    pub fn new() -> Self {
        Self::default()
    }

    /// Creates a source map builder.
    pub fn builder() -> SourceMapBuilder {
        SourceMapBuilder::new()
    }

    /// Returns the number of mappings in this source map.
    #[inline]
    pub fn len(&self) -> usize {
        self.mappings.len()
    }

    /// Returns true if this source map has no mappings.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.mappings.is_empty()
    }

    /// Returns an iterator over all mappings.
    pub fn mappings(&self) -> impl Iterator<Item = &Mapping> {
        self.mappings.iter()
    }

    /// Finds the original position corresponding to a generated position.
    ///
    /// Returns `None` if no mapping covers the given position.
    pub fn original_position(&self, generated: ByteOffset) -> Option<ByteOffset> {
        // Binary search for the mapping containing this position
        let mapping = self.find_mapping_for_generated(generated)?;

        // Calculate the offset within the generated span
        let offset_in_span = u32::from(generated) - u32::from(mapping.generated.start);

        // Apply the same offset to the original span
        Some(mapping.original.start + TextSize::from(offset_in_span))
    }

    /// Finds the generated position corresponding to an original position.
    ///
    /// Returns `None` if no mapping covers the given position.
    pub fn generated_position(&self, original: ByteOffset) -> Option<ByteOffset> {
        // Linear search since mappings are sorted by generated position
        for mapping in &self.mappings {
            if mapping.original.contains(original) {
                let offset_in_span = u32::from(original) - u32::from(mapping.original.start);
                return Some(mapping.generated.start + TextSize::from(offset_in_span));
            }
        }
        None
    }

    /// Re-aligns generated offsets after a set of byte edits were applied to the
    /// already-generated output *after* this map was built.
    ///
    /// Each edit is `(at, delta)` where `at` is the generated byte offset (in the
    /// pre-edit / as-built coordinate space) at which content was inserted or
    /// removed, and `delta` is `new_len - old_len` of the edited region. A
    /// positive delta means the output grew (e.g. an import specifier gained
    /// `../` segments); a negative delta means it shrank.
    ///
    /// For each edit, processed in ascending `at` order with a running cumulative
    /// shift:
    /// - mappings whose generated span starts at or after the edit point are
    ///   shifted by `delta`;
    /// - a mapping whose generated span *contains* the edit point is split into a
    ///   left part `[start, at)` (unchanged) and a right part `[at + delta,
    ///   end + delta)` whose original start is advanced by the left length, so
    ///   positions *after* the edited region still interpolate correctly. The
    ///   edited region itself carries no mapping (specifiers never host
    ///   diagnostics), which is acceptable.
    ///
    /// This keeps `original_position`/`generated_position` accurate against the
    /// post-edit text that a downstream type-checker actually sees.
    pub fn apply_generated_edits(&mut self, edits: &[(ByteOffset, i64)]) {
        if edits.is_empty() {
            return;
        }

        // Apply edits in ascending order of their (pre-edit) generated offset.
        let mut sorted: Vec<(ByteOffset, i64)> = edits.to_vec();
        sorted.sort_by_key(|(at, _)| *at);

        // Running shift accumulated from earlier edits, in bytes.
        let mut shift: i64 = 0;

        for (at, delta) in sorted {
            // Translate the pre-edit `at` into the current (already-shifted)
            // generated coordinate space of `self.mappings`.
            let at_shifted = apply_shift(at, shift);

            let mut next = Vec::with_capacity(self.mappings.len() + 1);
            for mapping in self.mappings.drain(..) {
                let g_start = mapping.generated.start;
                let g_end = mapping.generated.end;

                if g_start >= at_shifted {
                    // Entirely after the edit point: shift both ends by delta.
                    next.push(Mapping {
                        generated: Span::new(
                            apply_shift(g_start, delta),
                            apply_shift(g_end, delta),
                        ),
                        original: mapping.original,
                    });
                } else if g_end > at_shifted {
                    // The edit point falls strictly inside this mapping: split it.
                    let left_len = u32::from(at_shifted) - u32::from(g_start);
                    let orig_mid = mapping.original.start + TextSize::from(left_len);

                    // Left part: [g_start, at_shifted) -> unchanged original.
                    next.push(Mapping {
                        generated: Span::new(g_start, at_shifted),
                        original: Span::new(mapping.original.start, orig_mid),
                    });

                    // Right part: starts after the edited region in the generated
                    // text, but resumes from the same original position.
                    let right_gen_start = apply_shift(at_shifted, delta);
                    let right_gen_end = apply_shift(g_end, delta);
                    if right_gen_end > right_gen_start {
                        next.push(Mapping {
                            generated: Span::new(right_gen_start, right_gen_end),
                            original: Span::new(orig_mid, mapping.original.end),
                        });
                    }
                } else {
                    // Entirely before the edit point: untouched.
                    next.push(mapping);
                }
            }
            self.mappings = next;
            shift += delta;
        }

        // Restore the sorted-by-generated invariant for lookups.
        self.mappings.sort_by_key(|m| m.generated.start);
    }

    /// Finds the mapping that contains the given generated position.
    fn find_mapping_for_generated(&self, generated: ByteOffset) -> Option<&Mapping> {
        // Binary search for the first mapping where generated.start <= position
        let idx = match self
            .mappings
            .binary_search_by(|m| m.generated.start.cmp(&generated))
        {
            Ok(idx) => idx,
            Err(idx) => idx.saturating_sub(1),
        };

        self.mappings
            .get(idx)
            .filter(|m| m.generated.contains(generated))
    }
}

/// A builder for constructing source maps during transformation.
#[derive(Debug, Default)]
pub struct SourceMapBuilder {
    mappings: Vec<Mapping>,
    /// Current position in the generated output.
    generated_offset: ByteOffset,
}

impl SourceMapBuilder {
    /// Creates a new source map builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns the current generated offset.
    #[inline]
    pub fn generated_offset(&self) -> ByteOffset {
        self.generated_offset
    }

    /// Adds a mapping from an original span to the current generated position.
    ///
    /// The generated span will start at the current offset and have the given length.
    pub fn add_mapping(&mut self, original: Span, generated_len: u32) {
        let generated_start = self.generated_offset;
        let generated_end = generated_start + TextSize::from(generated_len);

        self.mappings.push(Mapping {
            generated: Span::new(generated_start, generated_end),
            original,
        });

        self.generated_offset = generated_end;
    }

    /// Adds verbatim source text, creating a 1:1 mapping.
    ///
    /// Use this when copying text from the original source unchanged.
    pub fn add_source(&mut self, original_start: ByteOffset, text: &str) {
        let len = text.len() as u32;
        let original = Span::new(original_start, original_start + TextSize::from(len));
        self.add_mapping(original, len);
    }

    /// Adds generated text without a corresponding original position.
    ///
    /// Use this for synthetic code that doesn't map back to source.
    pub fn add_generated(&mut self, text: &str) {
        self.generated_offset += TextSize::from(text.len() as u32);
    }

    /// Skips the given amount in generated output without adding a mapping.
    pub fn skip(&mut self, len: u32) {
        self.generated_offset += TextSize::from(len);
    }

    /// Adds transformed content where the generated text differs from the original.
    ///
    /// This creates a mapping from the original span to the generated text,
    /// even when they have different lengths. Useful for rune transformations.
    pub fn add_transformed(&mut self, original: Span, generated_text: &str) {
        let gen_len = generated_text.len() as u32;
        self.mappings.push(Mapping {
            generated: Span::new(
                self.generated_offset,
                self.generated_offset + TextSize::from(gen_len),
            ),
            original,
        });
        self.generated_offset += TextSize::from(gen_len);
    }

    /// Adds an expression with its original span, appending a semicolon.
    ///
    /// This is a convenience method for template expressions.
    pub fn add_expression(&mut self, original_span: Span, expression: &str) {
        // Map the expression
        self.add_transformed(original_span, expression);
        // Add untracked semicolon and newline
        self.add_generated(";\n");
    }

    /// Builds the final source map.
    pub fn build(mut self) -> SourceMap {
        // Sort mappings by generated position for efficient lookup
        self.mappings.sort_by_key(|m| m.generated.start);
        SourceMap {
            mappings: self.mappings,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_source_map() {
        let map = SourceMap::new();
        assert!(map.is_empty());
        assert_eq!(map.len(), 0);
    }

    #[test]
    fn test_builder_add_source() {
        let mut builder = SourceMapBuilder::new();
        builder.add_source(TextSize::from(0), "hello");
        builder.add_generated(" ");
        builder.add_source(TextSize::from(10), "world");

        let map = builder.build();
        assert_eq!(map.len(), 2);

        // "hello" at generated 0-5 maps to original 0-5
        assert_eq!(
            map.original_position(TextSize::from(0)),
            Some(TextSize::from(0))
        );
        assert_eq!(
            map.original_position(TextSize::from(4)),
            Some(TextSize::from(4))
        );

        // " " at generated 5-6 has no mapping
        assert_eq!(map.original_position(TextSize::from(5)), None);

        // "world" at generated 6-11 maps to original 10-15
        assert_eq!(
            map.original_position(TextSize::from(6)),
            Some(TextSize::from(10))
        );
    }

    #[test]
    fn test_apply_generated_edits_shifts_following_mapping() {
        // Two mappings: [0,5)->[0,5) and [10,15)->[100,105).
        let mut builder = SourceMapBuilder::new();
        builder.add_source(TextSize::from(0), "hello");
        builder.skip(5);
        builder.add_source(TextSize::from(100), "world");
        let mut map = builder.build();

        // Insert +3 bytes at generated offset 7 (between the two mappings).
        map.apply_generated_edits(&[(TextSize::from(7), 3)]);

        // First mapping is untouched.
        assert_eq!(
            map.original_position(TextSize::from(0)),
            Some(TextSize::from(0))
        );
        // Second mapping shifted by +3: now at generated [13,18).
        assert_eq!(
            map.original_position(TextSize::from(13)),
            Some(TextSize::from(100))
        );
        assert_eq!(
            map.original_position(TextSize::from(17)),
            Some(TextSize::from(104))
        );
    }

    #[test]
    fn test_apply_generated_edits_splits_covering_mapping() {
        // Single mapping covering generated [0,10) -> original [0,10).
        // The text is e.g. `'../foo'X` where the specifier `../foo` grows by +3
        // and a diagnostic-bearing token `X` follows on the same mapping.
        let mut builder = SourceMapBuilder::new();
        builder.add_source(TextSize::from(0), "0123456789");
        let mut map = builder.build();

        // Edit at generated offset 3 with delta +3 (specifier grows by 3 bytes).
        map.apply_generated_edits(&[(TextSize::from(3), 3)]);

        // Before the edit point: 1:1 unchanged.
        assert_eq!(
            map.original_position(TextSize::from(0)),
            Some(TextSize::from(0))
        );
        assert_eq!(
            map.original_position(TextSize::from(2)),
            Some(TextSize::from(2))
        );

        // The edited region [3,6) carries no mapping.
        assert_eq!(map.original_position(TextSize::from(4)), None);

        // After the edit point: a position that used to be generated 5 is now at
        // generated 5+3 = 8, and must still map back to original 5.
        assert_eq!(
            map.original_position(TextSize::from(8)),
            Some(TextSize::from(5))
        );
        // generated 12 (== old 9 + 3) -> original 9.
        assert_eq!(
            map.original_position(TextSize::from(12)),
            Some(TextSize::from(9))
        );
    }

    #[test]
    fn test_apply_generated_edits_multiple_cumulative() {
        // mapping A: [0,4)->[0,4); B: [4,8)->[50,54); C: [8,12)->[80,84).
        let mut builder = SourceMapBuilder::new();
        builder.add_source(TextSize::from(0), "AAAA");
        builder.add_source(TextSize::from(50), "BBBB");
        builder.add_source(TextSize::from(80), "CCCC");
        let mut map = builder.build();

        // Two edits: +3 inside A (at 1) and +2 inside B's start boundary (at 4).
        // After the first edit B and C shift by +3; the second edit (pre-edit
        // offset 4) must be re-based onto the shifted coordinate space.
        map.apply_generated_edits(&[(TextSize::from(1), 3), (TextSize::from(4), 2)]);

        // A left part unchanged.
        assert_eq!(
            map.original_position(TextSize::from(0)),
            Some(TextSize::from(0))
        );
        // A right part: old generated 3 -> 3+3 = 6 -> original 3.
        assert_eq!(
            map.original_position(TextSize::from(6)),
            Some(TextSize::from(3))
        );
        // B started at old generated 4; after +3 (first edit) it is at 7, then the
        // second edit (+2) lands exactly at its start, shifting it to 9.
        assert_eq!(
            map.original_position(TextSize::from(9)),
            Some(TextSize::from(50))
        );
        // C started at old generated 8; total shift is +5 -> 13 -> original 80.
        assert_eq!(
            map.original_position(TextSize::from(13)),
            Some(TextSize::from(80))
        );
    }

    #[test]
    fn test_apply_generated_edits_empty_is_noop() {
        let mut builder = SourceMapBuilder::new();
        builder.add_source(TextSize::from(0), "hello");
        let mut map = builder.build();
        map.apply_generated_edits(&[]);
        assert_eq!(
            map.original_position(TextSize::from(3)),
            Some(TextSize::from(3))
        );
    }

    #[test]
    fn test_reverse_lookup() {
        let mut builder = SourceMapBuilder::new();
        builder.add_source(TextSize::from(10), "hello");

        let map = builder.build();

        // Original position 10 → generated position 0
        assert_eq!(
            map.generated_position(TextSize::from(10)),
            Some(TextSize::from(0))
        );
        assert_eq!(
            map.generated_position(TextSize::from(14)),
            Some(TextSize::from(4))
        );
    }
}
